parameters:
#    kunstmaan_seo.example.class: Kunstmaan\SeoBundle\Example

services:
    kunstmaan_seo.twig.extension:
        class: Kunstmaan\SeoBundle\Twig\SeoTwigExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    kunstmaan_seo.google_analytics.twig.extension:
            class: Kunstmaan\SeoBundle\Twig\GoogleAnalyticsTwigExtension
            arguments: ["%google.analytics.account_id%"]
            tags:
                - { name: twig.extension }

    kunstmaan_seo.node.listener:
        class: Kunstmaan\SeoBundle\EventListener\NodeListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kunstmaan_node.adaptForm, method: adaptForm }

    kunstmaan_seo.clone.listener:
        class: Kunstmaan\SeoBundle\EventListener\CloneListener
        arguments: ["@doctrine.orm.entity_manager", "@kunstmaan_admin.clone.helper"]
        tags:
            - { name: kernel.event_listener, event: kunstmaan_admin.postDeepCloneAndSave, method: postDeepCloneAndSave }
